### ISSUE TITLE
Optionally ignore namespaces until explicitly added

### ISSUE THREAD

**Issue by brypete** [kubemod/kubemod#118]
Currently we can exclude namespaces via label `admission.kubemod.io/ignore=true`. However, this requires ignored namespaces to be known in advance of installation of kubemod. 

For situations where namespaces to be ignored are not known in advance, or where the cluster admin is wary of kubemod affecting resources unintentionally, it would be useful to have kubemod operate in a more restrictive "ignore all namespaces until explicitly added" mode.

**Comment by vassilvk** [comment]
The namespaces targeted by KubeMod are entirely controlled by the configuration of the KubeMod webhook configuration.
To switch from exclusive namespace targeting to inclusive targeting, replace the following two ([1](https://github.com/kubemod/kubemod/blob/4ad72f16918f611220caccba0b09e78f4441e19e/bundle.yaml#L536) and [2](https://github.com/kubemod/kubemod/blob/4ad72f16918f611220caccba0b09e78f4441e19e/bundle.yaml#L587)) `matchExpression` sections with the following:
```yaml
...
    - key: admission.kubemod.io/enable
      operator: In
      values:
      - "true"
...
```
Then make sure to add label `admission.kubemod.io/enable: "true"` to the namespaces you want watched by KubeMod.

**Comment by brypete** [comment]
Perfect, thanks!
