### ISSUE TITLE
Develop helm chart

### ISSUE THREAD

**Issue by vassilvk** [kubemod/kubemod#14]
Develop a helm chart for deploying kubemod operator.
 - Should support both Helm 2 and Helm 3.
 - Should trigger certificate generation job both on `install` and `upgrade`

**Comment by desaintmartin** [comment]
I'm working on https://github.com/wiremind/wiremind-helm-charts/pull/14, I would be more than happy to "donate" it when ready if you want. I had to tweak a bit (see the jobs and the ca secret generation...) and it depends on https://github.com/kubemod/kubemod-crt/pull/5.

**Comment by vassilvk** [comment]
@desaintmartin, that would be awesome!

I released [kubemod-crt 1.1.1](https://github.com/kubemod/kubemod-crt/releases/tag/v1.1.1) with your changes - please feel free to use that [image](https://hub.docker.com/layers/144012071/kubemod/kubemod-crt/v1.1.1/images/sha256-5eeef8e37c76672ac57624267ce5135104c01b926e0de7962fb604f372d0f1f6?context=explore).

**Comment by desaintmartin** [comment]
Thanks! I think the easiest idea would be to have a dedicated repository, like in https://github.com/oauth2-proxy/manifests, with CI/CD allowing to push new versions of the chart for each merged PR.

**Comment by desaintmartin** [comment]
I've created https://github.com/kubemod/kubemod-helm-chart and I am in the process of setting it up.

You can create an account on https://artifacthub.io, I'm going to publish the helm chart there.

**Comment by desaintmartin** [comment]
Done!
The chart is at https://github.com/kubemod/kubemod-helm-chart/tree/main/helm-chart/kubemod,
CI/CD is in place,
chart will appear soon in https://artifacthub.io (i.e in `helm search hub`).

**Comment by vassilvk** [comment]
@desaintmartin - great, thank you!

Let me test it over the weekend.
If I have any questions or find issues, I'll file in the new repo.

One little note - can you please rename the repo to `kubemod-helm`? Shorter is better :)

**Comment by desaintmartin** [comment]
Done at https://github.com/kubemod/kubemod-helm.
