### ISSUE TITLE
Add ability to match on .metadata.namespace

### ISSUE THREAD

**Issue by jamiecore** [kubemod/kubemod#52]
After implementing 
https://github.com/kubemod/kubemod/issues/51

It became apparent that I want ability to match on .metadata.namespace

AdmissionRequest has name (sometimes), namespace, and the resource spec 
Can patch the namespace into the resource spec so that isMatch() works ?

**Comment by vassilvk** [comment]
Hi @jamiecore, please see comment in #51.

**Comment by vassilvk** [comment]
Resolved by #51.
