### ISSUE TITLE
Update upgrade instructions to explicitly delete certificate generation job

### ISSUE THREAD

**Issue by jordiprats** [kubemod/kubemod#67]
Hi,
Checking the upgrade process here:

```
kubectl delete job -l job-name -n kubemod-system
```
The only Job I can find on the bundle is kubemod-crt-job, so I guess you mean:

```
kubectl delete job kubemod-crt-job -n kubemod-system
```

Is that right?

**Comment by vassilvk** [comment]
Hi @jordiprats,

Yes, in the context of KubeMod these commands are technically identical as the first one will remove all jobs, but `kubemod-crt-job` is the only job in the namespace.

I will update the README to use the more explicit (and clear) command you posted here.
