### ISSUE TITLE
Existing Resources

### ISSUE THREAD

**Issue by juanr2001** [kubemod/kubemod#92]
If I have an `existing` deployment already deployed in kubernetes, `then` I created / deployed a ModRule , can kubemod have the ability to change the `metadata.labels.example` value of of the existing deployment?

**Comment by vassilvk** [comment]
Hi @jamiecore,

Kubemod is a mutating admission hook. As such, it can only detect (and modify) resources at the time they are created or updated. Pre-existing resources are not subject to those modifications until an update operation is performed against their manifest.

**Comment by juanr2001** [comment]
@jamiecore thank you kind lord!

**Comment by vassilvk** [comment]
Whoops, sorry, I meant to say @juanr2001!
I guess I have @jamiecore on speed dial :)

**Comment by vassilvk** [comment]
Hi @juanr2001,

Did the above answer your question?
If yes, please close the issue.

**Comment by vassilvk** [comment]
Closing.
@juanr2001, please reopen in case you decide to continue the discussion.
